version: "3"
services:
    sw:
        network_mode: host
        image: pentahojava:1.0.0
#CMD ["/bin/sh", "/usr/local/sw/workbench.sh"]
        entrypoint: /usr/local/sw/workbench.sh
        environment:
            - DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /etc/localtime:/etc/localtime:ro
            - ${VOLUMES_DIR}/pentaho/sw/bin/9.2/schema-workbench:/usr/local/sw

