version: "3"
services:
    spoon:
        network_mode: host
        image: spoonjava:1.0.0
        environment:
            - DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /etc/localtime:/etc/localtime:ro
            - ${VOLUMES_DIR}/pentaho/pdi/versions/9.1/data-integration:/usr/local/pdi
            - ${VOLUMES_DIR}/pentaho/pdi/files:/usr/local/files
            - ${VOLUMES_DIR}/pentaho/pdi/backup:/usr/local/backup
            - ${VOLUMES_DIR}/pentaho/pdi/kettle_props:/root/.kettle
