version: "3"
services:
    spoon:
        build: .
        environment:
            - DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /etc/localtime:/etc/localtime:ro
            - ../pdi/versions/9.1/data-integration:/usr/local/pdi/9.1/data-integration
            - ../pdi/files:/usr/local/files
            - ../pdi/backup:/usr/local/backup
            - ../pdi/kettle_props:/root/.kettle
        networks:
            - pdi_network
networks:
    pdi_network:
        external: true
