#docker build -t spoondocker:1.0.0 . --network=host
FROM debian:9
#RUN apt-get update
#RUN apt-get install libwebkitgtk-1.0-0 -y
RUN echo 'deb http://ftp.de.debian.org/debian sid main' >> /etc/apt/sources.list
RUN apt-get update
#RUN apt-get install default-jre -y
RUN apt-get install libssl1.0.0apt-get install libssl1.0.0
RUN apt-get install openjdk-8-jdk -y
WORKDIR /usr/local
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 \
    OPT=-Doracle.jdbc.timezoneAsRegion=false
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
CMD ["/bin/sh", "/usr/local/pdi/spoon.sh"]
