version: "3"
services:
    spoon:
        image: spoonjava:1.0.0
        environment:
            - DISPLAY
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix
            - /etc/localtime:/etc/localtime:ro
            - ../pdi/versions/9.1/data-integration:/usr/local/pdi
            - ../pdi/files:/usr/local/files
            - ../pdi/backup:/usr/local/backup
            - ../pdi/kettle_props:/root/.kettle
        networks:
            - main_network
networks:
    main_network:
        external: true
