version: "3"
services:
    pdi_crontab:
        build: .
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ../pdi/versions/9.1/data-integration:/usr/local/pdi
            - ../pdi/files:/usr/local/files
            - ../pdi/backup:/usr/local/backup
            - ../pdi/kettle_props:/root/.kettle
            - ./scripts:/usr/local/scripts
        networks:
            - pdi_network
networks:
    pdi_network:
        external: true
