version: "3"
services:
    pdi_master:
        build: .
        volumes:
            - ${VOLUMES_DIR}/pentaho/pdi/versions/9.1/data-integration:/usr/local/pdi
            - ${VOLUMES_DIR}/pentaho/pdi/files:/usr/local/files
            - ${VOLUMES_DIR}/pentaho/pdi/backup:/usr/local/backup
            - ${VOLUMES_DIR}/pentaho/pdi/kettle_props:/root/.kettle
        ports:
            - "8088:8080"
        restart: always
