version: '3'
services:
  webspoon:
    image: hiromuhota/webspoon
    container_name: webspoon
    ports:
      - "8000:8080"
    volumes:
      - /kettle:/home/tomcat/.kettle
      - /pentaho:/home/tomcat/.pentaho
    environment:
      - "JAVA_OPTS=-Xms1024m -Xmx2048m"
    networks:
      - pdi_network
networks:
  pdi_network:
    external: true
