version: "3"
services:
    pdi_repo_postgres:
        restart: always
        image: postgres
        ports:
            - 5432:5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: pdi
            POSTGRES_PASSWORD: p3nt4h0
            POSTGRES_DB: pdi
            PGDATA: /var/lib/postgresql/data
        networks:
            - pdi_network
networks:
    pdi_network:
        external: true

